server {
  listen 8080;
  listen 3000;
  server_name localhost;

  root /usr/share/nginx/html;

  location / {
      try_files $uri index.html $uri/ =404;
  }

  location ~ ^/docs/[0-9a-fA-F-]+/?$ {
      try_files $uri /docs/[id]/index.html;
  }

  error_page 404 /404.html;
  location = /404.html {
      internal;
  }
}
