services:
  frontend:
    user: "${DOCKER_USER:-1000}"
    build:
      context: .
      dockerfile: ./src/frontend/Dockerfile
      target: frontend-production
      args:
        API_ORIGIN: "http://localhost:8071"
        PUBLISH_AS_MIT: "false"
        SW_DEACTIVATED: "true"
    image: impress:frontend-production
    ports:
      - "3000:3000"

  yhub:
    user: ${DOCKER_USER:-1000}
    build:
      context: .
      dockerfile: ./src/frontend/servers/yhub/Dockerfile
      target: yhub
    image: impress:yhub-production
    restart: unless-stopped
    environment:
      - REDIS_URL=redis://redis:6379
      - POSTGRES_URL=postgres://dinum:pass@postgresql:5432/impress
    env_file:
      - env.d/development/common
      - env.d/development/common.local
    ports:
      - "4444:4444"
    depends_on:
      redis:
        condition: service_healthy
      postgresql:
        condition: service_healthy

  y-provider-converter:
    user: ${DOCKER_USER:-1000}
    build:
      context: .
      dockerfile: ./src/frontend/servers/y-provider/Dockerfile
      target: y-provider
    image: impress:y-provider-production
    restart: unless-stopped
    env_file:
      - env.d/development/common
      - env.d/development/common.local
