{{- $fullName := include "impress.fullname" . -}}
{{- $component := "media" -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ $fullName }}-media
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "impress.common.labels" (list . $component) | nindent 4 }}
  annotations:
    {{- toYaml $.Values.serviceMedia.annotations | nindent 4 }}
spec:
  ports:
    - name: http
      port: 9000
      protocol: TCP
      targetPort: 9000
  selector:
    app.kubernetes.io/component: frontend
    app.kubernetes.io/instance: impress
    app.kubernetes.io/name: docs
  sessionAffinity: None
  type: ClusterIP
