packages:
  - apps/*
  - packages/*
  - servers/*

overrides:
  '@socialgouv/e2esdk-client': link:../../../../../../Library/pnpm/global/5/node_modules/@socialgouv/e2esdk-client
  '@socialgouv/e2esdk-devtools': link:../../../../../../Library/pnpm/global/5/node_modules/@socialgouv/e2esdk-devtools
  '@socialgouv/e2esdk-react': link:../../../../../../Library/pnpm/global/5/node_modules/@socialgouv/e2esdk-react
  '@tiptap/extensions': 3.14.0
  '@types/node': 24.10.9
  '@types/react': 19.2.8
  '@types/react-dom': 19.2.3
  eslint: 9.39.2
  prosemirror-view: 1.41.4
  react: 19.2.3
  react-dom: 19.2.3
  typescript: 5.9.3
  wrap-ansi: 9.0.2
  yjs: 13.6.29
