# Generated by Django 5.2.3 on 2025-07-13 08:22

from django.db import migrations, models

import core.validators


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0023_remove_document_is_public_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="linktrace",
            name="is_masked",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="user",
            name="language",
            field=models.CharField(
                blank=True,
                choices=[
                    ("en-us", "English"),
                    ("fr-fr", "Français"),
                    ("de-de", "Deutsch"),
                    ("nl-nl", "Nederlands"),
                    ("es-es", "Español"),
                ],
                default=None,
                help_text="The language in which the user wants to see the interface.",
                max_length=10,
                null=True,
                verbose_name="language",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="sub",
            field=models.CharField(
                blank=True,
                help_text="Required. 255 characters or fewer. ASCII characters only.",
                max_length=255,
                null=True,
                unique=True,
                validators=[core.validators.sub_validator],
                verbose_name="sub",
            ),
        ),
    ]
