# Generated by Django 5.2.7 on 2025-10-22 06:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0024_add_is_masked_field_to_link_trace"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="short_name",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="short name"
            ),
        ),
    ]
