# Generated by Django 5.2.4 on 2025-09-03 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_alter_document_link_role_alter_documentaccess_role_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.JSONField(),
        ),
    ]
