# Generated by Django 5.2.7 on 2025-11-29 06:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0025_outline_import_job"),
        ("core", "0026_comments"),
    ]

    operations = []
