# Generated by Django 5.2.9 on 2026-01-09 14:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0027_auto_20251120_0956"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="templateaccess",
            name="template",
        ),
        migrations.RemoveField(
            model_name="templateaccess",
            name="user",
        ),
        migrations.DeleteModel(
            name="Template",
        ),
        migrations.DeleteModel(
            name="TemplateAccess",
        ),
    ]
