# Generated by Django 5.2.9

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0027_merge_0025_outline_import_job_0026_comments"),
        ("core", "0028_remove_templateaccess_template_and_more"),
    ]

    operations = []
