# Generated by Django 5.2.10 on 2026-02-23 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_remove_templateaccess_template_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='is_encrypted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='documentaccess',
            name='encrypted_document_symmetric_key_for_user',
            field=models.TextField(blank=True, help_text='Encrypted symmetric key for this document, specific to this user.', null=True, verbose_name='encrypted document symmetric key'),
        ),
        migrations.AddField(
            model_name='user',
            name='encryption_public_key',
            field=models.TextField(blank=True, help_text='Public key for end-to-end encryption.', null=True, verbose_name='encryption public key'),
        ),
    ]
