# Generated by Django 5.2.11 on 2026-03-02 11:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0029_userreconciliationcsvimport_userreconciliation"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_first_connection",
            field=models.BooleanField(
                default=True,
                help_text="Whether the user has completed the first connection process.",
                verbose_name="first connection completed",
            ),
        ),
    ]
