# Generated by Django 5.2.11 on 2026-03-04 14:49

from django.db import migrations, models


def set_is_first_connection_false(apps, schema_editor):
    """Update all existing user.is_first_connection to False."""
    user = apps.get_model("core", "User")

    user.objects.update(is_first_connection=False)


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0029_userreconciliationcsvimport_userreconciliation"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_first_connection",
            field=models.BooleanField(
                default=True,
                help_text="Whether the user has completed the first connection process.",
                verbose_name="first connection status",
            ),
        ),
        migrations.RunPython(
            set_is_first_connection_false,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
