# Generated by Django 5.2.12 on 2026-03-11 17:16

from django.conf import settings
from django.db import migrations

from core.models import PRIVILEGED_ROLES


def clean_onboarding_accesses(apps, schema_editor):
    """clean accesses on on-boarding documents."""
    onboarding_document_ids = settings.USER_ONBOARDING_DOCUMENTS
    if not onboarding_document_ids:
        return

    onboarding_document_ids = set(settings.USER_ONBOARDING_DOCUMENTS)

    DocumentAccess = apps.get_model("core", "DocumentAccess")

    DocumentAccess.objects.filter(document_id__in=onboarding_document_ids).exclude(
        role__in=PRIVILEGED_ROLES
    ).delete()


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0030_user_is_first_connection"),
    ]

    operations = [
        migrations.RunPython(
            clean_onboarding_accesses,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
