# Generated by Django 5.2.14 on 2026-05-28 14:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0031_clean_onboarding_accesses"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="linktrace",
            name="is_masked",
        ),
    ]
