# Generated by Django 5.2.14 on 2026-08-19 14:36

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0032_remove_linktrace_is_masked"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="document",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["attachments"], name="document_attachments_gin"
            ),
        ),
    ]
