# Generated by Django 5.2.14 on 2026-07-24 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_remove_linktrace_is_masked'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='document',
            options={'ordering': ('-created_at',), 'verbose_name': 'Document', 'verbose_name_plural': 'Documents'},
        ),
        migrations.RemoveConstraint(
            model_name='document',
            name='check_deleted_at_matches_ancestors_deleted_at_when_set',
        ),
        migrations.RemoveField(
            model_name='document',
            name='ancestors_deleted_at',
        ),
        migrations.RemoveField(
            model_name='document',
            name='depth',
        ),
        migrations.RemoveField(
            model_name='document',
            name='duplicated_from',
        ),
        migrations.RemoveField(
            model_name='document',
            name='excerpt',
        ),
        migrations.RemoveField(
            model_name='document',
            name='has_deleted_children',
        ),
        migrations.RemoveField(
            model_name='document',
            name='link_reach',
        ),
        migrations.RemoveField(
            model_name='document',
            name='link_role',
        ),
        migrations.RemoveField(
            model_name='document',
            name='numchild',
        ),
        migrations.RemoveField(
            model_name='document',
            name='path',
        ),
    ]
