# Generated by Django 5.2.14 on 2026-07-27 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_alter_document_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invitation',
            name='document',
        ),
        migrations.RemoveField(
            model_name='invitation',
            name='issuer',
        ),
        migrations.DeleteModel(
            name='DocumentAccess',
        ),
        migrations.DeleteModel(
            name='Invitation',
        ),
    ]
